# apiVersion: "serving.kserve.io/v1beta1"
# kind: "InferenceService"
# metadata:
#   name: "imagenet-vit"
# spec:
#   predictor:
#     serviceAccountName: s3-read-only
#     model:
#       modelFormat:
#         name: pytorch
#       storageUri: s3://emlo-session23/imagenet-vit/
#       resources:
#         limits:
#           cpu: 2600m
#           memory: 4Gi

apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "imagenet-vit"
  annotations:
    serving.kserve.io/enable-metric-aggregation: "true"
    serving.kserve.io/enable-prometheus-scraping: "true"
spec:
  predictor:
    # canaryTrafficPercent: 40
    serviceAccountName: s3-read-only
    model:
      modelFormat:
        name: pytorch
      storageUri: s3://emlo-session23/food-classifier/
      resources:
        limits:
          cpu: 2600m
          memory: 4Gi